app = "movie-sentiment-analyzer"
primary_region = "sin"

[build]

[env]
  PORT = "8000"
  PYTHONPATH = "."

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  grace_period = "5s"
  method = "GET"
  path = "/api/health"

[processes]
  app = "uvicorn app:app --host 0.0.0.0 --port 8000"
