services:
  - type: web
    name: movie-sentiment-analyzer
    env: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "8000"
    
    # Render uses the Dockerfile at repo root by default
    # If you later need to override the start command, uncomment below:
    # dockerCommand: uvicorn backend.app:app --host 0.0.0.0 --port $PORT
